site_name: ROS on Windows
repo_url: https://github.com/ms-iot/rosonwindows/
edit_uri: edit/master/docs/
nav:
    - Home: index.md
    - What's New: WhatsNew.md
    - Build Status: Build/buildfarm.md
    - Get ROS:
        - Binary Installation: GettingStarted/Setup.md
    - Using ROS:
        - For new ROS Users: GettingStarted/NewToROS.md
    - Tutorials:
        - Tutorials at ROS Wiki &nearr;: http://wiki.ros.org/ROS/Tutorials
        - MoveIt: Moveit/moveit_tutorials.md
        - Universal Robot UR3: Moveit/UR3.md
        - TurtleBot 3: Turtlebot/Turtlebot3.md
        - SICK S300: tutorials/sick_s300/getting_started.md
        - Simple Open EtherCAT Master: tutorials/ethercat/soem.md
    - CI/CD Practices:
        - Continuous Integration Template: GettingStarted/SetupCI.md
    - Porting Guide:
        - Consuming a ROS Package: GettingStarted/UsingROSonWindows.md
        - Porting a ROS Package: GettingStarted/PortingANode.md
        - Using a C++ Dependency: GettingStarted/UsingVCPKG.md
        - Porting a C++ Dependency: GettingStarted/AddingVCPKG.md
        - Porting Cookbook: Porting/Cookbook.md
    - ROS at Microsoft:
        - ROS 1 Azure VM: ROSAtMS/ROS1AzureVM.md
        - Windows ML ROS Node: ROSAtMS/WinML.md
        - Azure Kinect ROS Node &nearr;: https://github.com/microsoft/azure_kinect_ros_driver
        - Azure IoT Hub Node &nearr;: https://github.com/microsoft/ros_azure_iothub
        - Visual Studio Code ROS Extension &nearr;: https://aka.ms/ros/vscode
    - Advanced:
        - Source Installation: Build/source.md
    - Support:
        - Troubleshooting: GettingStarted/Troubleshooting.md
        - Create Issue: https://github.com/ms-iot/rosonwindows/issues
        - Paid Support: https://aka.ms/ros/support
theme: readthedocs
use_directory_urls: false
strict: true
